<?php
/**
 * Creates (or resets the password of) every account in TestUsers::ROLES and
 * writes the credentials to local/config/persons-test.env.
 *
 *   ddev exec php plugins/persons/tests/Support/create-test-users.php
 *
 * Idempotent: run it again to rotate the passwords. It talks to the database
 * directly rather than through pwg.users.add, because that method needs a
 * webmaster session - which is the thing this script exists to hand out.
 *
 * Passwords are generated, printed nowhere, and land only in a git-ignored file.
 *
 * It also marks the install as a throwaway. The persons suites create and
 * delete albums and photos and rewrite the metadata of image files, and
 * FixtureBuilder refuses to run without that marker - so this script is the
 * single place that says "losing this gallery costs nothing".
 *
 * Never point this at a production database.
 */

require_once __DIR__ . '/Config.php';
require_once __DIR__ . '/Db.php';
require_once __DIR__ . '/TestUsers.php';

$piwigoRoot = dirname(__DIR__, 4) . '/';
require_once $piwigoRoot . 'include/passwordhash.class.php';

$db = new Db();
$hasher = new PasswordHash(13, true);

/** A user_infos row to clone defaults from, so this script does not restate the schema. */
$template = $db->query('SELECT * FROM piwigo_user_infos ORDER BY user_id LIMIT 1')->fetch_assoc();
if ($template === null)
{
    fwrite(STDERR, "No user_infos row to take defaults from - is this a real Piwigo install?\n");
    exit(1);
}

// Declares the install expendable. FixtureBuilder refuses to build a fixture
// without this row; see assertThrowawayInstall() for what the suites do to a
// gallery and why the guard is unconditional.
$db->query(
    "INSERT INTO piwigo_config (param, value, comment)
     VALUES ('persons_throwaway_install', '1', 'Set by plugins/persons/tests/Support/create-test-users.php. The persons suites destroy gallery content; never set this on a production install.')
     ON DUPLICATE KEY UPDATE value = '1'"
);
if ((string)$db->scalar("SELECT value FROM piwigo_config WHERE param = 'persons_throwaway_install'") !== '1')
{
    fwrite(STDERR, "Could not mark this install as a throwaway; the suites will refuse to run.\n");
    exit(1);
}

$lines = array();

foreach (TestUsers::ROLES as $username => $status)
{
    $password = bin2hex(random_bytes(16));
    $hash = $hasher->HashPassword($password);
    $escapedName = $db->escape($username);

    $userId = $db->scalar("SELECT id FROM piwigo_users WHERE username = '$escapedName'");

    if ($userId === null)
    {
        $db->query(
            "INSERT INTO piwigo_users (username, password, mail_address)
             VALUES ('$escapedName', '" . $db->escape($hash) . "', '$escapedName@example.invalid')"
        );
        $userId = $db->insertId();
    }
    else
    {
        $userId = (int)$userId;
        $db->query("UPDATE piwigo_users SET password = '" . $db->escape($hash) . "' WHERE id = $userId");
    }

    $level = $status === 'webmaster' ? 8 : 0;

    $hasInfos = $db->scalar("SELECT user_id FROM piwigo_user_infos WHERE user_id = $userId");
    if ($hasInfos === null)
    {
        $row = $template;
        $row['user_id'] = $userId;
        $row['status'] = $status;
        $row['level'] = $level;
        $row['registration_date'] = date('Y-m-d H:i:s');
        $row['activation_key'] = null;
        $row['activation_key_expire'] = null;
        $row['last_visit'] = null;

        $columns = array();
        $values = array();
        foreach ($row as $column => $value)
        {
            $columns[] = "`$column`";
            $values[] = $value === null ? 'NULL' : "'" . $db->escape((string)$value) . "'";
        }
        $db->query(
            'INSERT INTO piwigo_user_infos (' . implode(', ', $columns) . ')
             VALUES (' . implode(', ', $values) . ')'
        );
    }
    else
    {
        $db->query("UPDATE piwigo_user_infos SET status = '$status', level = $level WHERE user_id = $userId");
    }

    // Assert the state took effect rather than trusting the writes above.
    $actual = $db->scalar("SELECT status FROM piwigo_user_infos WHERE user_id = $userId");
    if ($actual !== $status)
    {
        fwrite(STDERR, "Failed to give $username status $status (got: " . var_export($actual, true) . ")\n");
        exit(1);
    }

    list($userVar, $passVar) = TestUsers::envVars($username);
    $lines[] = "$userVar=$username";
    $lines[] = "$passVar=$password";

    echo "ok  $username ($status, user_id $userId)\n";
}

$envPath = $piwigoRoot . TestUsers::ENV_FILE;
@mkdir(dirname($envPath), 0777, true);
file_put_contents(
    $envPath,
    "# Generated by plugins/persons/tests/Support/create-test-users.php\n" .
    "# Git-ignored. Re-run that script to rotate these.\n" .
    implode("\n", $lines) . "\n"
);
chmod($envPath, 0600);

echo "\ncredentials written to " . TestUsers::ENV_FILE . "\n";
